### ISSUE TITLE
Identity not initialized on Ganache

### ISSUE THREAD

**Issue by innovatielab** [uport-project/uport-cli-client#4]
I've funded the given address on Ganache test network, but this is happening:

```
 Please fund the following address: 

 0x2e178d6fda79ce37a27ddb8a1215a0e3a52e55cf 

 Then your identity can be created 

? Press y to continue:  Yes
Initializing identity... 

(node:82110) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'data' of undefined
    at consume.then.then.receipt (/usr/local/lib/node_modules/uport-cli-client/node_modules/uport-client/index.js:316:57)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)
(node:82110) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:82110) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I'm on node version 9.9.0. 
When doing this on i.e. Kovan things are going fine...
Also, the uport-js-client library is working as well

**Comment by kamescg** [comment]
@innovatielab Thank you for submitting the issue.

I'll review the error this week and report back with my findings.
