### ISSUE TITLE
CLI UI Breaking 

### ISSUE THREAD

**Issue by kaviyarasu7** [uport-project/uport-cli-client#5]
I am trying to create an identity in my private network using cli-client but it throws below error 

![capture](https://user-images.githubusercontent.com/5144291/38085358-d8462ed2-336d-11e8-95fd-b3130ce09f81.PNG)

root@Demo-Server:~/uport-identity# uport-id create kavi123
? Choose a network for your identity: Custom Network
? Do you want to deploy the uport platform contracts on this network?  (Y/n)
You selected Custom Network, the following is the default configuration:

 {}

? Do you want to deploy the uport platform contracts on this network?  Yes
? Do you want to change the default configuration?  Yes
? Do you want to deploy the uport platform contracts on this network?  No
? Enter rpcUrl:  http://13.127.47.96:8545/
? Is this ipfs configuration what you want to use?  (Y/n) (node:27883) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'rpcUrl' of undefined
    at inquirer.prompt.then.then.answers (/usr/lib/node_modules/uport-cli-client/uport-id.js:88:47)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:27883) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:27883) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by subhodi** [comment]
Facing the same issue in following environments
OS: Windows, node: v 8.11.0
OS: Ubuntu, node: v8.11.0 and v9.7.1

**Comment by ollip1** [comment]
About same happening here 
OS: Mac, Node: v10.3.0

Initializing identity... 

(node:4646) UnhandledPromiseRejectionWarning: Error: [ethjs-query] while formatting outputs from RPC '{"value":{"message":"Attempting to run transaction which calls a contract function, but recipient address 0x0ddd27df7dd974920876dec2891b19c2ebfc37b9 is not a contract address","code":-32000,"data":{"stack":"Error\n    at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/lib/statemanager.js:819:1\n    at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/lib/statemanager.js:259:1\n    at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/lib/blockchain_double.js:992:1\n    at e.exports.c.getCode (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ethereumjs-account/index.js:45:1)\n    at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/ganache-core/lib/blockchain_double.js:989:1\n    at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/baseTrie.js:93:1\n    at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/baseTrie.js:524:1\n    at Object.return (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/baseTrie.js:489:1)\n    at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/baseTrie.js:305:1\n    at e (/Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/baseTrie.js:519:1)\n    at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/baseTrie.js:519:1\n    at /Applications/Ganache.app/Contents/Resources/app.asar/node_modules/ganache-cli/build/webpack:/ganache/node_modules/merkle-patricia-tree/baseTrie.js:188:1\n    at _combinedTickCallback (internal/process/next_tick.js:131:7)\n    at process._tickCallback (internal/process/next_tick.js:180:9)","name":"n"}}}'
    at /usr/local/lib/node_modules/uport-cli-client/node_modules/ethjs-query/lib/index.js:108:29
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:4646) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4646) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
